services:
  db:
    image: "postgres:17"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -d polls -U $$POSTGRES_USER"
      ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "polls"
    volumes:
      - ./db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1gb
  app:
    build:
      context: .  # the location of the Dockerfile
      args:
        SECRET_KEY: "${SECRET_KEY}"
    image: ku-polls
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py loaddata data/polls-v4.json data/votes-v4.json data/users.json
        python manage.py runserver 0.0.0.0:8000
    env_file: docker.env
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          memory: 256mb


